{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.megatronking.stringfog",
    "module": "interface",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "interface-5.0.1.jar",
          "url": "interface-5.0.1.jar",
          "size": 9904,
          "sha512": "a4cdd5b45f14c5fdec16377b6d38541c338531b15d1949df76153cb9b38c3b4636ffed3c29924da29a681f14fbef8f1370c2d49f310b720522473a4692627e0f",
          "sha256": "35c7a1f0bfd4e9b29b9a74e8fe23f4e3cb6e5243534be94847a1847b5b4a58bb",
          "sha1": "e698dec913fd860a9de3ece1aa99a601a7247bbe",
          "md5": "d6613b5e4cdee3aa87a9cd1ce3aea66f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interface-5.0.1.jar",
          "url": "interface-5.0.1.jar",
          "size": 9904,
          "sha512": "a4cdd5b45f14c5fdec16377b6d38541c338531b15d1949df76153cb9b38c3b4636ffed3c29924da29a681f14fbef8f1370c2d49f310b720522473a4692627e0f",
          "sha256": "35c7a1f0bfd4e9b29b9a74e8fe23f4e3cb6e5243534be94847a1847b5b4a58bb",
          "sha1": "e698dec913fd860a9de3ece1aa99a601a7247bbe",
          "md5": "d6613b5e4cdee3aa87a9cd1ce3aea66f"
        }
      ]
    }
  ]
}
